DROP TABLE IF EXISTS to_dos CASCADE;

CREATE TABLE to_dos (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  lists_id INTEGER REFERENCES lists(id) ON DELETE CASCADE,
  to_do_name VARCHAR(255) NOT NULL,
  to_do_type VARCHAR(50),
  to_do_description VARCHAR(10000),
  input TEXT
);
4
